export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST'
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS'
export const FETCH_ISSUES_ERROR = 'FETCH_ISSUES_ERROR'

export const FETCH_REPORT_REQUEST = 'FETCH_REPORT_REQUEST'
export const FETCH_REPORT_SUCCESS = 'FETCH_REPORT_SUCCESS'
export const FETCH_REPORT_ERROR = 'FETCH_REPORT_ERROR'

export const SUBMIT_REPORT_REQUEST = 'SUBMIT_REPORT_REQUEST'
export const SUBMIT_REPORT_SUCCESS = 'SUBMIT_REPORT_SUCCESS'
export const SUBMIT_REPORT_ERROR = 'SUBMIT_REPORT_ERROR'

export const FETCH_LOCATIONBYIP_REQUEST = 'FETCH_LOCATIONBYIP_REQUEST'
export const FETCH_LOCATIONBYIP_SUCCESS = 'FETCH_LOCATIONBYIP_SUCCESS'
export const FETCH_LOCATIONBYIP_ERROR = 'FETCH_LOCATIONBYIP_ERROR'

export const SET_FETCH_LOCATION_BY = 'SET_FETCH_LOCATION_BY'
export const SET_ALLOW_BROWSER_GEOLOCATION = 'SET_ALLOW_BROWSER_GEOLOCATION'
export const SET_BROWSER_GEOLOCATION = 'SET_BROWSER_GEOLOCATION'

export const SET_REMOTE_DATA = 'SET_REMOTEDATA'
export const SET_REPORT_DATA = 'SET_REPORTDATA'
export const SET_LOCATION_INFO = 'SET_LOCATION_INFO'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_USERSTATS = 'SET_USERSTATS'
export const SET_CALLSTATE = 'SET_CALLSTATE'

export const SELECT_ISSUE = 'SELECT_ISSUE'
export const COMPLETE_ISSUE = 'COMPLETE_ISSUE'
export const MOVE_TO_NEXT_CONTACT = 'MOVE_TO_NEXT_CONTACT'
export const SET_ASKING_LOCATION = 'SET_ASKING_LOCATION'
export const SET_FETCHING_LOCATION = 'SET_FETCHING_LOCATION'

// Development functionality
export const SET_ISDEBUG = 'SET_ISDEBUG'
// resets local user stats and completed issues
export const RESET_ISSUES = 'RESET_ISSUES'
export const RESET_LOCATION = 'RESET_LOCATION'